// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: outputs/laptime.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtobufMsgs {

  /// <summary>Holder for reflection information generated from outputs/laptime.proto</summary>
  public static partial class LaptimeReflection {

    #region Descriptor
    /// <summary>File descriptor for outputs/laptime.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LaptimeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVvdXRwdXRzL2xhcHRpbWUucHJvdG8SDXByb3RvYnVmX21zZ3MiNgoNTGFw",
            "VGltZU91dHB1dBIPCgdsYXBUaW1lGAEgASgEEhQKDGxhcFN0YXJ0VGltZRgC",
            "IAEoBEIQWg5hc2UvcGJfb3V0cHV0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufMsgs.LapTimeOutput), global::ProtobufMsgs.LapTimeOutput.Parser, new[]{ "LapTime", "LapStartTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class LapTimeOutput : pb::IMessage<LapTimeOutput> {
    private static readonly pb::MessageParser<LapTimeOutput> _parser = new pb::MessageParser<LapTimeOutput>(() => new LapTimeOutput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LapTimeOutput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufMsgs.LaptimeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LapTimeOutput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LapTimeOutput(LapTimeOutput other) : this() {
      lapTime_ = other.lapTime_;
      lapStartTime_ = other.lapStartTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LapTimeOutput Clone() {
      return new LapTimeOutput(this);
    }

    /// <summary>Field number for the "lapTime" field.</summary>
    public const int LapTimeFieldNumber = 1;
    private ulong lapTime_;
    /// <summary>
    /// Time of complete lap in ms
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong LapTime {
      get { return lapTime_; }
      set {
        lapTime_ = value;
      }
    }

    /// <summary>Field number for the "lapStartTime" field.</summary>
    public const int LapStartTimeFieldNumber = 2;
    private ulong lapStartTime_;
    /// <summary>
    /// Start of the lap
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong LapStartTime {
      get { return lapStartTime_; }
      set {
        lapStartTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LapTimeOutput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LapTimeOutput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LapTime != other.LapTime) return false;
      if (LapStartTime != other.LapStartTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LapTime != 0UL) hash ^= LapTime.GetHashCode();
      if (LapStartTime != 0UL) hash ^= LapStartTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LapTime != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(LapTime);
      }
      if (LapStartTime != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(LapStartTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LapTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(LapTime);
      }
      if (LapStartTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(LapStartTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LapTimeOutput other) {
      if (other == null) {
        return;
      }
      if (other.LapTime != 0UL) {
        LapTime = other.LapTime;
      }
      if (other.LapStartTime != 0UL) {
        LapStartTime = other.LapStartTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LapTime = input.ReadUInt64();
            break;
          }
          case 16: {
            LapStartTime = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
