// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tuning/tuning.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtobufMsgs {

  /// <summary>Holder for reflection information generated from tuning/tuning.proto</summary>
  public static partial class TuningReflection {

    #region Descriptor
    /// <summary>File descriptor for tuning/tuning.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TuningReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChN0dW5pbmcvdHVuaW5nLnByb3RvEg1wcm90b2J1Zl9tc2dzIuoCCgtUdW5p",
            "bmdTdGF0ZRIRCgl0aW1lc3RhbXAYASABKAQSPwoRZHluYW1pY1BhcmFtZXRl",
            "cnMYAiADKAsyJC5wcm90b2J1Zl9tc2dzLlR1bmluZ1N0YXRlLlBhcmFtZXRl",
            "chqGAgoJUGFyYW1ldGVyEkYKBm51bWJlchgBIAEoCzI0LnByb3RvYnVmX21z",
            "Z3MuVHVuaW5nU3RhdGUuUGFyYW1ldGVyLk51bWJlclBhcmFtZXRlckgAEkYK",
            "BnN0cmluZxgDIAEoCzI0LnByb3RvYnVmX21zZ3MuVHVuaW5nU3RhdGUuUGFy",
            "YW1ldGVyLlN0cmluZ1BhcmFtZXRlckgAGi0KD051bWJlclBhcmFtZXRlchIL",
            "CgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAIaLQoPU3RyaW5nUGFyYW1ldGVy",
            "EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCUILCglwYXJhbWV0ZXJCD1oN",
            "YXNlL3BiX3R1bmluZ2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufMsgs.TuningState), global::ProtobufMsgs.TuningState.Parser, new[]{ "Timestamp", "DynamicParameters" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufMsgs.TuningState.Types.Parameter), global::ProtobufMsgs.TuningState.Types.Parameter.Parser, new[]{ "Number", "String" }, new[]{ "Parameter" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufMsgs.TuningState.Types.Parameter.Types.NumberParameter), global::ProtobufMsgs.TuningState.Types.Parameter.Types.NumberParameter.Parser, new[]{ "Key", "Value" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufMsgs.TuningState.Types.Parameter.Types.StringParameter), global::ProtobufMsgs.TuningState.Types.Parameter.Types.StringParameter.Parser, new[]{ "Key", "Value" }, null, null, null, null)})})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TuningState : pb::IMessage<TuningState> {
    private static readonly pb::MessageParser<TuningState> _parser = new pb::MessageParser<TuningState>(() => new TuningState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TuningState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufMsgs.TuningReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TuningState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TuningState(TuningState other) : this() {
      timestamp_ = other.timestamp_;
      dynamicParameters_ = other.dynamicParameters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TuningState Clone() {
      return new TuningState(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private ulong timestamp_;
    /// <summary>
    /// increased when the state changes, used to prevent unnecessary updates (so *not* in milliseconds since epoch)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "dynamicParameters" field.</summary>
    public const int DynamicParametersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ProtobufMsgs.TuningState.Types.Parameter> _repeated_dynamicParameters_codec
        = pb::FieldCodec.ForMessage(18, global::ProtobufMsgs.TuningState.Types.Parameter.Parser);
    private readonly pbc::RepeatedField<global::ProtobufMsgs.TuningState.Types.Parameter> dynamicParameters_ = new pbc::RepeatedField<global::ProtobufMsgs.TuningState.Types.Parameter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ProtobufMsgs.TuningState.Types.Parameter> DynamicParameters {
      get { return dynamicParameters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TuningState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TuningState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      if(!dynamicParameters_.Equals(other.dynamicParameters_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      hash ^= dynamicParameters_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Timestamp);
      }
      dynamicParameters_.WriteTo(output, _repeated_dynamicParameters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      size += dynamicParameters_.CalculateSize(_repeated_dynamicParameters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TuningState other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      dynamicParameters_.Add(other.dynamicParameters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 18: {
            dynamicParameters_.AddEntriesFrom(input, _repeated_dynamicParameters_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the TuningState message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Parameter : pb::IMessage<Parameter> {
        private static readonly pb::MessageParser<Parameter> _parser = new pb::MessageParser<Parameter>(() => new Parameter());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Parameter> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ProtobufMsgs.TuningState.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Parameter() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Parameter(Parameter other) : this() {
          switch (other.ParameterCase) {
            case ParameterOneofCase.Number:
              Number = other.Number.Clone();
              break;
            case ParameterOneofCase.String:
              String = other.String.Clone();
              break;
          }

          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Parameter Clone() {
          return new Parameter(this);
        }

        /// <summary>Field number for the "number" field.</summary>
        public const int NumberFieldNumber = 1;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::ProtobufMsgs.TuningState.Types.Parameter.Types.NumberParameter Number {
          get { return parameterCase_ == ParameterOneofCase.Number ? (global::ProtobufMsgs.TuningState.Types.Parameter.Types.NumberParameter) parameter_ : null; }
          set {
            parameter_ = value;
            parameterCase_ = value == null ? ParameterOneofCase.None : ParameterOneofCase.Number;
          }
        }

        /// <summary>Field number for the "string" field.</summary>
        public const int StringFieldNumber = 3;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::ProtobufMsgs.TuningState.Types.Parameter.Types.StringParameter String {
          get { return parameterCase_ == ParameterOneofCase.String ? (global::ProtobufMsgs.TuningState.Types.Parameter.Types.StringParameter) parameter_ : null; }
          set {
            parameter_ = value;
            parameterCase_ = value == null ? ParameterOneofCase.None : ParameterOneofCase.String;
          }
        }

        private object parameter_;
        /// <summary>Enum of possible cases for the "parameter" oneof.</summary>
        public enum ParameterOneofCase {
          None = 0,
          Number = 1,
          String = 3,
        }
        private ParameterOneofCase parameterCase_ = ParameterOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ParameterOneofCase ParameterCase {
          get { return parameterCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearParameter() {
          parameterCase_ = ParameterOneofCase.None;
          parameter_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Parameter);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Parameter other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Number, other.Number)) return false;
          if (!object.Equals(String, other.String)) return false;
          if (ParameterCase != other.ParameterCase) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (parameterCase_ == ParameterOneofCase.Number) hash ^= Number.GetHashCode();
          if (parameterCase_ == ParameterOneofCase.String) hash ^= String.GetHashCode();
          hash ^= (int) parameterCase_;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (parameterCase_ == ParameterOneofCase.Number) {
            output.WriteRawTag(10);
            output.WriteMessage(Number);
          }
          if (parameterCase_ == ParameterOneofCase.String) {
            output.WriteRawTag(26);
            output.WriteMessage(String);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (parameterCase_ == ParameterOneofCase.Number) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Number);
          }
          if (parameterCase_ == ParameterOneofCase.String) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(String);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Parameter other) {
          if (other == null) {
            return;
          }
          switch (other.ParameterCase) {
            case ParameterOneofCase.Number:
              if (Number == null) {
                Number = new global::ProtobufMsgs.TuningState.Types.Parameter.Types.NumberParameter();
              }
              Number.MergeFrom(other.Number);
              break;
            case ParameterOneofCase.String:
              if (String == null) {
                String = new global::ProtobufMsgs.TuningState.Types.Parameter.Types.StringParameter();
              }
              String.MergeFrom(other.String);
              break;
          }

          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                global::ProtobufMsgs.TuningState.Types.Parameter.Types.NumberParameter subBuilder = new global::ProtobufMsgs.TuningState.Types.Parameter.Types.NumberParameter();
                if (parameterCase_ == ParameterOneofCase.Number) {
                  subBuilder.MergeFrom(Number);
                }
                input.ReadMessage(subBuilder);
                Number = subBuilder;
                break;
              }
              case 26: {
                global::ProtobufMsgs.TuningState.Types.Parameter.Types.StringParameter subBuilder = new global::ProtobufMsgs.TuningState.Types.Parameter.Types.StringParameter();
                if (parameterCase_ == ParameterOneofCase.String) {
                  subBuilder.MergeFrom(String);
                }
                input.ReadMessage(subBuilder);
                String = subBuilder;
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the Parameter message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types {
          /// <summary>
          /// note: it may seem weird to not extract the key from the oneof, but this is so that the parser can easily determine the type of the parameter
          /// extracting it to a separate field on the same level as oneof would make it ambiguous
          /// </summary>
          public sealed partial class NumberParameter : pb::IMessage<NumberParameter> {
            private static readonly pb::MessageParser<NumberParameter> _parser = new pb::MessageParser<NumberParameter>(() => new NumberParameter());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pb::MessageParser<NumberParameter> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::ProtobufMsgs.TuningState.Types.Parameter.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public NumberParameter() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public NumberParameter(NumberParameter other) : this() {
              key_ = other.key_;
              value_ = other.value_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public NumberParameter Clone() {
              return new NumberParameter(this);
            }

            /// <summary>Field number for the "key" field.</summary>
            public const int KeyFieldNumber = 1;
            private string key_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string Key {
              get { return key_; }
              set {
                key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "value" field.</summary>
            public const int ValueFieldNumber = 2;
            private float value_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public float Value {
              get { return value_; }
              set {
                value_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override bool Equals(object other) {
              return Equals(other as NumberParameter);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public bool Equals(NumberParameter other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Key != other.Key) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Value, other.Value)) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override int GetHashCode() {
              int hash = 1;
              if (Key.Length != 0) hash ^= Key.GetHashCode();
              if (Value != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Value);
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void WriteTo(pb::CodedOutputStream output) {
              if (Key.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(Key);
              }
              if (Value != 0F) {
                output.WriteRawTag(21);
                output.WriteFloat(Value);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int CalculateSize() {
              int size = 0;
              if (Key.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
              }
              if (Value != 0F) {
                size += 1 + 4;
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(NumberParameter other) {
              if (other == null) {
                return;
              }
              if (other.Key.Length != 0) {
                Key = other.Key;
              }
              if (other.Value != 0F) {
                Value = other.Value;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    Key = input.ReadString();
                    break;
                  }
                  case 21: {
                    Value = input.ReadFloat();
                    break;
                  }
                }
              }
            }

          }

          public sealed partial class StringParameter : pb::IMessage<StringParameter> {
            private static readonly pb::MessageParser<StringParameter> _parser = new pb::MessageParser<StringParameter>(() => new StringParameter());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pb::MessageParser<StringParameter> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::ProtobufMsgs.TuningState.Types.Parameter.Descriptor.NestedTypes[1]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public StringParameter() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public StringParameter(StringParameter other) : this() {
              key_ = other.key_;
              value_ = other.value_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public StringParameter Clone() {
              return new StringParameter(this);
            }

            /// <summary>Field number for the "key" field.</summary>
            public const int KeyFieldNumber = 1;
            private string key_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string Key {
              get { return key_; }
              set {
                key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "value" field.</summary>
            public const int ValueFieldNumber = 2;
            private string value_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string Value {
              get { return value_; }
              set {
                value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override bool Equals(object other) {
              return Equals(other as StringParameter);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public bool Equals(StringParameter other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Key != other.Key) return false;
              if (Value != other.Value) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override int GetHashCode() {
              int hash = 1;
              if (Key.Length != 0) hash ^= Key.GetHashCode();
              if (Value.Length != 0) hash ^= Value.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void WriteTo(pb::CodedOutputStream output) {
              if (Key.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(Key);
              }
              if (Value.Length != 0) {
                output.WriteRawTag(18);
                output.WriteString(Value);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int CalculateSize() {
              int size = 0;
              if (Key.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
              }
              if (Value.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(StringParameter other) {
              if (other == null) {
                return;
              }
              if (other.Key.Length != 0) {
                Key = other.Key;
              }
              if (other.Value.Length != 0) {
                Value = other.Value;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    Key = input.ReadString();
                    break;
                  }
                  case 18: {
                    Value = input.ReadString();
                    break;
                  }
                }
              }
            }

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
