name: Build and release roverlib-c-sharp

on:
    release:
        types: [published]

permissions:
    contents: write
    packages: write

jobs:

    build-roverlib-c-sharp:
        name: Build roverlib-c-sharp
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
          
            - name: Build inside the docker container
              env:
                  VERSION: ${{ env.VERSION }}
              run: |
                  docker build --build-arg HOST_UID=$(id -u) -t bulid_image -f .devcontainer/Dockerfile .
                  docker run -e --rm --user dev -v "$(pwd):/workspace/roverlib-c-sharp:z" bulid_image bash -ic 'make build -C /workspace/roverlib-c-sharp'
                  zip -r roverlib-c-sharp.zip roverlib-c-sharp

            - name: Debug print
              run: |
                  ls -lah
                  file roverlib-c-sharp*

            # Upload asset
            - uses: AButler/upload-release-assets@v3.0
              with:
                  files: roverlib-c-sharp.zip
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  release-tag: ${{ env.VERSION }}

